# Generated by Django 2.1.5 on 2020-02-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_remove_page_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
